### ISSUE TITLE
Login button redirects to `https://vpm-beta.vlang.io/`

### ISSUE THREAD

**Issue by ArtemkaKun** [vlang/vpm#39]
After login from the `https://vpm.vlang.io/` page, the `https://vpm-beta.vlang.io/` page is opened and all operations are performed on this domain.

If I manually return to `https://vpm.vlang.io/` - I'm no more logged in

**Comment by medvednikov** [comment]
Fixed.

**Comment by ArtemkaKun** [comment]
Error still present

Before login

![image](https://user-images.githubusercontent.com/36485221/236805822-45082d66-ecca-447f-b1e5-99ed105b6beb.png)

After login

![image](https://user-images.githubusercontent.com/36485221/236805933-93e21cf1-c4e1-49f7-a17c-f368b082299d.png)
